### ISSUE TITLE
Add basic screen controls

### ISSUE THREAD

**Issue by VantorreWannes** [JokNavi/Raster-Console#3]
## Todo:

- [x] Add a grow() method to increase the screen size.
- [x] Add a shrink() method to decrease the screen size.
- [ ] Add a resize() method that appropriately calls shrink() or grow().
- [ ] Add a write() method that writes to a coord key in the screen dict and fills it with a value.
- [ ] Add a get() method that gets the value at a certain key.
- [ ] Add a print() method that prints the whole screen.
- [ ] Add debug methods that show information about the screen such as name() or size() showing the respective screen name and height and width.
